[package]
name = "codeprompt-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
tui-tree-widget = "0.23.0"
anyhow = "1.0.86"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0.1"
toml = "0.8"
